use crate::accent::Accent;
use crate::replacement::Replacement;
use crate::source::Source;
use crate::target::MultiTarget;

pub struct Scotsman {
    replacements: Vec<Replacement>,
}

impl Accent for Scotsman {
    fn replacements(&self) -> &[Replacement] {
        &self.replacements
    }
}

impl Scotsman {
    pub fn new() -> Result<Self, String> {
        Ok(Self {
            replacements: vec![
                Replacement::new(Source::Raw(r"$(?<!```)\z"), Box::new(" ye daft cunt"))?,
                Replacement::new(Source::Raw(r"\babout\b"), Box::new("aboot"))?,
                Replacement::new(Source::Raw(r"\babove\b"), Box::new("`boon"))?,
                Replacement::new(Source::Raw(r"\baccounts\b"), Box::new("accoonts"))?,
                Replacement::new(Source::Raw(r"\bacross\b"), Box::new("o`er"))?,
                Replacement::new(Source::Raw(r"\bafter\b"), Box::new("efter"))?,
                Replacement::new(Source::Raw(r"\bagree\b"), Box::new("gree"))?,
                Replacement::new(Source::Raw(r"\ball\b"), Box::new("aw"))?,
                Replacement::new(Source::Raw(r"\balmost\b"), Box::new("a`maist"))?,
                Replacement::new(Source::Raw(r"\balong\b"), Box::new("alang"))?,
                Replacement::new(Source::Raw(r"\balready\b"), Box::new("awready"))?,
                Replacement::new(Source::Raw(r"\balso\b"), Box::new("an` a`"))?,
                Replacement::new(Source::Raw(r"\balthough\b"), Box::new("althoogh"))?,
                Replacement::new(Source::Raw(r"\band\b"), Box::new("`n`"))?,
                Replacement::new(Source::Raw(r"\banother\b"), Box::new("anither"))?,
                Replacement::new(Source::Raw(r"\bany\b"), Box::new("ony"))?,
                Replacement::new(Source::Raw(r"\banyone\b"), Box::new("a`body"))?,
                Replacement::new(Source::Raw(r"\banybody\b"), Box::new("a`body"))?,
                Replacement::new(Source::Raw(r"\banything\b"), Box::new("anythin`"))?,
                Replacement::new(Source::Raw(r"\barrested\b"), Box::new("liftit"))?,
                Replacement::new(Source::Raw(r"\barrest\b"), Box::new("lift"))?,
                Replacement::new(Source::Raw(r"\barrests\b"), Box::new("lifts"))?,
                Replacement::new(Source::Raw(r"\bargues\b"), Box::new("argies"))?,
                Replacement::new(Source::Raw(r"\bargued\b"), Box::new("argied"))?,
                Replacement::new(Source::Raw(r"\bargue\b"), Box::new("argie"))?,
                Replacement::new(Source::Raw(r"\baround\b"), Box::new("aroond"))?,
                Replacement::new(Source::Raw(r"\bavailable\b"), Box::new("free"))?,
                Replacement::new(Source::Raw(r"\bavoiding\b"), Box::new("jookin"))?,
                Replacement::new(Source::Raw(r"\bavoided\b"), Box::new("jooked"))?,
                Replacement::new(Source::Raw(r"\bavoid\b"), Box::new("jook"))?,
                Replacement::new(Source::Raw(r"\bask\b"), Box::new("spir"))?,
                Replacement::new(Source::Raw(r"\bassistant\b"), Box::new("servand"))?,
                Replacement::new(Source::Raw(r"\bassistants\b"), Box::new("servands"))?,
                Replacement::new(Source::Raw(r"\basking\b"), Box::new("spirin"))?,
                Replacement::new(Source::Raw(r"\basked\b"), Box::new("spire'd"))?,
                Replacement::new(Source::Raw(r"\baway\b"), Box::new("awa`"))?,
                Replacement::new(Source::Raw(r"\bbabies\b"), Box::new("bairns"))?,
                Replacement::new(Source::Raw(r"\bbaby\b"), Box::new("bairn"))?,
                Replacement::new(Source::Raw(r"\bbad\b"), Box::new("ill"))?,
                Replacement::new(Source::Raw(r"\bballs\b"), Box::new("baws"))?,
                Replacement::new(Source::Raw(r"\bball\b"), Box::new("baw"))?,
                Replacement::new(Source::Raw(r"\bbars\b"), Box::new("boozers"))?,
                Replacement::new(Source::Raw(r"\bbar\b"), Box::new("boozer"))?,
                Replacement::new(Source::Raw(r"\bbeen\b"), Box::new("buin"))?,
                Replacement::new(Source::Raw(r"\bbeautiful\b"), Box::new("bonny"))?,
                Replacement::new(Source::Raw(r"\bbecause\b"), Box::new("fur"))?,
                Replacement::new(Source::Raw(r"\bbreakdown\b"), Box::new("breakdoon"))?,
                Replacement::new(Source::Raw(r"\bnap\b"), Box::new("kip"))?,
                Replacement::new(Source::Raw(r"\bnapping\b"), Box::new("kipin'"))?,
                Replacement::new(Source::Raw(r"\bbefore\b"), Box::new("afore"))?,
                Replacement::new(Source::Raw(r"\bbelieves\b"), Box::new("hawps"))?,
                Replacement::new(Source::Raw(r"\bbelieving\b"), Box::new("hawpin"))?,
                Replacement::new(Source::Raw(r"\bbelieve\b"), Box::new("hawp"))?,
                Replacement::new(Source::Raw(r"\bbetween\b"), Box::new("atween"))?,
                Replacement::new(Source::Raw(r"\bboards\b"), Box::new("boords"))?,
                Replacement::new(Source::Raw(r"\bboard\b"), Box::new("boord"))?,
                Replacement::new(Source::Raw(r"\bboth\b"), Box::new("baith"))?,
                Replacement::new(Source::Raw(r"\bboxes\b"), Box::new("kists"))?,
                Replacement::new(Source::Raw(r"\bbox\b"), Box::new("kist"))?,
                Replacement::new(Source::Raw(r"\bboy\b"), Box::new("laddie"))?,
                Replacement::new(Source::Raw(r"\bbrother\b"), Box::new("brither"))?,
                Replacement::new(Source::Raw(r"\bbrothers\b"), Box::new("brithers"))?,
                Replacement::new(Source::Raw(r"\bbut\b"), Box::new("bit"))?,
                Replacement::new(Source::Raw(r"\bbitch\b"), Box::new("cunt"))?,
                Replacement::new(Source::Raw(r"\bcaptain\b"), Box::new("caiptain"))?,
                Replacement::new(Source::Raw(r"\bcap\b"), Box::new("caip"))?,
                Replacement::new(Source::Raw(r"\bcalling\b"), Box::new("ca`ing"))?,
                Replacement::new(Source::Raw(r"\bcalled\b"), Box::new("cawed"))?,
                Replacement::new(Source::Raw(r"\bcall\b"), Box::new("caw"))?,
                Replacement::new(Source::Raw(r"\bcars\b"), Box::new("motors"))?,
                Replacement::new(Source::Raw(r"\bcar\b"), Box::new("motor"))?,
                Replacement::new(Source::Raw(r"\bcared\b"), Box::new("car'd"))?,
                Replacement::new(Source::Raw(r"\bcards\b"), Box::new("cairds"))?,
                Replacement::new(Source::Raw(r"\bcard\b"), Box::new("caird"))?,
                Replacement::new(Source::Raw(r"\bcareers\b"), Box::new("joabs"))?,
                Replacement::new(Source::Raw(r"\bcareer\b"), Box::new("joab"))?,
                Replacement::new(Source::Raw(r"\bcargo\b"), Box::new("cargae"))?,
                Replacement::new(Source::Raw(r"\bcentury\b"), Box::new("hunner years"))?,
                Replacement::new(Source::Raw(r"\bchanged\b"), Box::new("chaynged"))?,
                Replacement::new(Source::Raw(r"\bchange\b"), Box::new("chaynge"))?,
                Replacement::new(Source::Raw(r"\bchaplain\b"), Box::new("priestheid"))?,
                Replacement::new(Source::Raw(r"\bchief\b"), Box::new("heid"))?,
                Replacement::new(Source::Raw(r"\bchild\b"), Box::new("wee'un"))?,
                Replacement::new(Source::Raw(r"\bchilderen\b"), Box::new("wee'uns"))?,
                Replacement::new(Source::Raw(r"\bchoosing\b"), Box::new("walin"))?,
                Replacement::new(Source::Raw(r"\bchoose\b"), Box::new("wale"))?,
                Replacement::new(Source::Raw(r"\bchurches\b"), Box::new("kirks"))?,
                Replacement::new(Source::Raw(r"\bchurch\b"), Box::new("kirk"))?,
                Replacement::new(Source::Raw(r"\bcity\b"), Box::new("toon"))?,
                Replacement::new(Source::Raw(r"\bcities\b"), Box::new("toons"))?,
                Replacement::new(Source::Raw(r"\bcloser\b"), Box::new("claiser"))?,
                Replacement::new(Source::Raw(r"\bclosest\b"), Box::new("claisest"))?,
                Replacement::new(Source::Raw(r"\bclose\b"), Box::new("claise"))?,
                Replacement::new(Source::Raw(r"\bclowns\b"), Box::new("clouns"))?,
                Replacement::new(Source::Raw(r"\bclown\b"), Box::new("cloun"))?,
                Replacement::new(Source::Raw(r"\bcoats\b"), Box::new("coaties"))?,
                Replacement::new(Source::Raw(r"\bcoat\b"), Box::new("coatie"))?,
                Replacement::new(Source::Raw(r"\bcoldest\b"), Box::new("cauldest"))?,
                Replacement::new(Source::Raw(r"\bcolder\b"), Box::new("caulder"))?,
                Replacement::new(Source::Raw(r"\bcold\b"), Box::new("cauld"))?,
                Replacement::new(Source::Raw(r"\bcooks\b"), Box::new("keuks"))?,
                Replacement::new(Source::Raw(r"\bcook\b"), Box::new("keuk"))?,
                Replacement::new(Source::Raw(r"\bconsumer\b"), Box::new("punter"))?,
                Replacement::new(Source::Raw(r"\bconsumers\b"), Box::new("punters"))?,
                Replacement::new(Source::Raw(r"\bcould\b"), Box::new("cuid"))?,
                Replacement::new(Source::Raw(r"\bcountries\b"), Box::new("lands"))?,
                Replacement::new(Source::Raw(r"\bcountry\b"), Box::new("land"))?,
                Replacement::new(Source::Raw(r"\bcourse\b"), Box::new("coorse"))?,
                Replacement::new(Source::Raw(r"\bcourses\b"), Box::new("coorses"))?,
                Replacement::new(Source::Raw(r"\bcultures\b"), Box::new("culchurs"))?,
                Replacement::new(Source::Raw(r"\bculture\b"), Box::new("culchur"))?,
                Replacement::new(Source::Raw(r"\bcustomer\b"), Box::new("punter"))?,
                Replacement::new(Source::Raw(r"\bcustomers\b"), Box::new("punters"))?,
                Replacement::new(Source::Raw(r"\bdaddy\b"), Box::new("daddie"))?,
                Replacement::new(Source::Raw(r"\bdark\b"), Box::new("mirk"))?,
                Replacement::new(Source::Raw(r"\bdad\b"), Box::new("da"))?,
                Replacement::new(Source::Raw(r"\bdead\b"), Box::new("deid"))?,
                Replacement::new(Source::Raw(r"\bdeaf\b"), Box::new("deav"))?,
                Replacement::new(Source::Raw(r"\bdeafen\b"), Box::new("deave"))?,
                Replacement::new(Source::Raw(r"\bdeafened\b"), Box::new("deaved"))?,
                Replacement::new(Source::Raw(r"\bdebate\b"), Box::new("argie"))?,
                Replacement::new(Source::Raw(r"\bdebating\b"), Box::new("argiein"))?,
                Replacement::new(Source::Raw(r"\bdebates\b"), Box::new("argies"))?,
                Replacement::new(Source::Raw(r"\bdegrees\b"), Box::new("grees"))?,
                Replacement::new(Source::Raw(r"\bdegree\b"), Box::new("gree"))?,
                Replacement::new(Source::Raw(r"\bdetectives\b"), Box::new("snoots"))?,
                Replacement::new(Source::Raw(r"\bdetective\b"), Box::new("snoot"))?,
                Replacement::new(Source::Raw(r"\bdifficult\b"), Box::new("pernicketie"))?,
                Replacement::new(Source::Raw(r"\bdinner\b"), Box::new("tea"))?,
                Replacement::new(Source::Raw(r"\bdirectors\b"), Box::new("guiders"))?,
                Replacement::new(Source::Raw(r"\bdirector\b"), Box::new("guider"))?,
                Replacement::new(Source::Raw(r"\bdid\b"), Box::new("daed"))?,
                Replacement::new(Source::Raw(r"\bdo\b"), Box::new("dae"))?,
                Replacement::new(Source::Raw(r"\bdogs\b"), Box::new("dugs"))?,
                Replacement::new(Source::Raw(r"\bdog\b"), Box::new("dug"))?,
                Replacement::new(Source::Raw(r"\bdown\b"), Box::new("doon"))?,
                Replacement::new(Source::Raw(r"\bdownricht\b"), Box::new("doun"))?,
                Replacement::new(Source::Raw(r"\bdroped\b"), Box::new("draped"))?,
                Replacement::new(Source::Raw(r"\bdrops\b"), Box::new("draps"))?,
                Replacement::new(Source::Raw(r"\bdrop\b"), Box::new("drap"))?,
                Replacement::new(Source::Raw(r"\bdrink\b"), Box::new("drappie"))?,
                Replacement::new(Source::Raw(r"\bdrinking\b"), Box::new("swillin'"))?,
                Replacement::new(Source::Raw(r"\bdrank\b"), Box::new("swilled"))?,
                Replacement::new(Source::Raw(r"\bdrunk\b"), Box::new("fou"))?,
                Replacement::new(Source::Raw(r"\bduring\b"), Box::new("while"))?,
                Replacement::new(Source::Raw(r"\bdying\b"), Box::new("deein'"))?,
                Replacement::new(Source::Raw(r"\beach\b"), Box::new("ilk"))?,
                Replacement::new(Source::Raw(r"\bearly\b"), Box::new("earlie"))?,
                Replacement::new(Source::Raw(r"\beating\b"), Box::new("slochin"))?,
                Replacement::new(Source::Raw(r"\bate\b"), Box::new("sloched"))?,
                Replacement::new(Source::Raw(r"\beat\b"), Box::new("sloch"))?,
                Replacement::new(Source::Raw(r"\bedges\b"), Box::new("lips"))?,
                Replacement::new(Source::Raw(r"\bedge\b"), Box::new("lip"))?,
                Replacement::new(Source::Raw(r"\benjoys\b"), Box::new("gilravages"))?,
                Replacement::new(Source::Raw(r"\benjoy\b"), Box::new("gilravage"))?,
                Replacement::new(Source::Raw(r"\bengineer\b"), Box::new("navvy"))?,
                Replacement::new(Source::Raw(r"\bengineering\b"), Box::new("ingineerin"))?,
                Replacement::new(Source::Raw(r"\bengineers\b"), Box::new("Navvies"))?,
                Replacement::new(Source::Raw(r"\bevenings\b"), Box::new("forenichts"))?,
                Replacement::new(Source::Raw(r"\bevening\b"), Box::new("forenicht"))?,
                Replacement::new(Source::Raw(r"\bevery\b"), Box::new("ilka"))?,
                Replacement::new(Source::Raw(r"\beverybody\b"), Box::new("a`body"))?,
                Replacement::new(Source::Raw(r"\beveryone\b"), Box::new("a`body"))?,
                Replacement::new(Source::Raw(r"\beye\b"), Box::new("ee"))?,
                Replacement::new(Source::Raw(r"\beyes\b"), Box::new("e'ens"))?,
                Replacement::new(Source::Raw(r"\bface\b"), Box::new("physog"))?,
                Replacement::new(Source::Raw(r"\bfamililies\b"), Box::new("fowks"))?,
                Replacement::new(Source::Raw(r"\bfamily\b"), Box::new("fowk"))?,
                Replacement::new(Source::Raw(r"\bfast\b"), Box::new("fleet"))?,
                Replacement::new(Source::Raw(r"\bfathers\b"), Box::new("faithers"))?,
                Replacement::new(Source::Raw(r"\bfather\b"), Box::new("faither"))?,
                Replacement::new(Source::Raw(r"\bfight\b"), Box::new("rammy"))?,
                Replacement::new(Source::Raw(r"\bfighting\b"), Box::new("ramming"))?,
                Replacement::new(Source::Raw(r"\bfights\b"), Box::new("rammies"))?,
                Replacement::new(Source::Raw(r"\bfilms\b"), Box::new("pictures"))?,
                Replacement::new(Source::Raw(r"\bfilm\b"), Box::new("picture"))?,
                Replacement::new(Source::Raw(r"\bfinding\b"), Box::new("fin`ing"))?,
                Replacement::new(Source::Raw(r"\bfound\b"), Box::new("fund"))?,
                Replacement::new(Source::Raw(r"\bfine\b"), Box::new("braw"))?,
                Replacement::new(Source::Raw(r"\bfloors\b"), Box::new("flairs"))?,
                Replacement::new(Source::Raw(r"\bfloor\b"), Box::new("flair"))?,
                Replacement::new(Source::Raw(r"\bfoods\b"), Box::new("fairns"))?,
                Replacement::new(Source::Raw(r"\bfood\b"), Box::new("fairn"))?,
                Replacement::new(Source::Raw(r"\bfor\b"), Box::new("fer"))?,
                Replacement::new(Source::Raw(r"\bforget\b"), Box::new("forgoat"))?,
                Replacement::new(Source::Raw(r"\bfriends\b"), Box::new("mukkers"))?,
                Replacement::new(Source::Raw(r"\bfriend\b"), Box::new("pal"))?,
                Replacement::new(Source::Raw(r"\bfrom\b"), Box::new("fae"))?,
                Replacement::new(Source::Raw(r"\bfull\b"), Box::new("stowed oot"))?,
                Replacement::new(Source::Raw(r"\bgames\b"), Box::new("gams"))?,
                Replacement::new(Source::Raw(r"\bgame\b"), Box::new("gam"))?,
                Replacement::new(Source::Raw(r"\bgardens\b"), Box::new("back greens"))?,
                Replacement::new(Source::Raw(r"\bgarden\b"), Box::new("back green"))?,
                Replacement::new(Source::Raw(r"\bget\b"), Box::new("git"))?,
                Replacement::new(Source::Raw(r"\bgirl\b"), Box::new("lassie"))?,
                Replacement::new(Source::Raw(r"\bgive\b"), Box::new("gie"))?,
                Replacement::new(Source::Raw(r"\bglasses\b"), Box::new("glesses"))?,
                Replacement::new(Source::Raw(r"\bglass\b"), Box::new("gless"))?,
                Replacement::new(Source::Raw(r"\bgo\b"), Box::new("gae"))?,
                Replacement::new(Source::Raw(r"\bgood\b"), Box::new("guid"))?,
                Replacement::new(Source::Raw(r"\bgreat\b"), Box::new("stoatin"))?,
                Replacement::new(Source::Raw(r"\bgrowing\b"), Box::new("grawing"))?,
                Replacement::new(Source::Raw(r"\bgrown\b"), Box::new("grawn"))?,
                Replacement::new(Source::Raw(r"\bgrow\b"), Box::new("graw"))?,
                Replacement::new(Source::Raw(r"\bglared\b"), Box::new("glower'd"))?,
                Replacement::new(Source::Raw(r"\bglaring\b"), Box::new("glowrin'"))?,
                Replacement::new(Source::Raw(r"\bguess\b"), Box::new("jalouse"))?,
                Replacement::new(Source::Raw(r"\bhad\b"), Box::new("haed"))?,
                Replacement::new(Source::Raw(r"\bhas\b"), Box::new("haes"))?,
                Replacement::new(Source::Raw(r"\bhadnt\b"), Box::new("haedna"))?,
                Replacement::new(Source::Raw(r"\bhadn't\b"), Box::new("haedna"))?,
                Replacement::new(Source::Raw(r"\bhairs\b"), Box::new("locks"))?,
                Replacement::new(Source::Raw(r"\bhair\b"), Box::new("locks"))?,
                Replacement::new(Source::Raw(r"\bhalfs\b"), Box::new("haufs"))?,
                Replacement::new(Source::Raw(r"\bhalf\b"), Box::new("hauf"))?,
                Replacement::new(Source::Raw(r"\bhands\b"), Box::new("hauns"))?,
                Replacement::new(Source::Raw(r"\bhand\b"), Box::new("haun"))?,
                Replacement::new(Source::Raw(r"\bhangs\b"), Box::new("hings"))?,
                Replacement::new(Source::Raw(r"\bhanging\b"), Box::new("hinging"))?,
                Replacement::new(Source::Raw(r"\bhang\b"), Box::new("hing"))?,
                Replacement::new(Source::Raw(r"\bhave\b"), Box::new("hae"))?,
                Replacement::new(Source::Raw(r"\bheads\b"), Box::new("heids"))?,
                Replacement::new(Source::Raw(r"\bhead\b"), Box::new("heid"))?,
                Replacement::new(Source::Raw(r"\bhearts\b"), Box::new("herts"))?,
                Replacement::new(Source::Raw(r"\bheart\b"), Box::new("hert"))?,
                Replacement::new(Source::Raw(r"\bhelp\b"), Box::new("hulp"))?,
                Replacement::new(Source::Raw(r"\bhere\b"), Box::new("`ere"))?,
                Replacement::new(Source::Raw(r"\bhigh\b"), Box::new("heich"))?,
                Replacement::new(Source::Raw(r"\bhimself\b"), Box::new("his-sel"))?,
                Replacement::new(Source::Raw(r"\bholding\b"), Box::new("hauding"))?,
                Replacement::new(Source::Raw(r"\bhold\b"), Box::new("haud"))?,
                Replacement::new(Source::Raw(r"\bhomes\b"), Box::new("hames"))?,
                Replacement::new(Source::Raw(r"\bhome\b"), Box::new("hame"))?,
                Replacement::new(Source::Raw(r"\bhopes\b"), Box::new("hawps"))?,
                Replacement::new(Source::Raw(r"\bhope\b"), Box::new("hawp"))?,
                Replacement::new(Source::Raw(r"\bhoter\b"), Box::new("heter"))?,
                Replacement::new(Source::Raw(r"\bhotest\b"), Box::new("hetest"))?,
                Replacement::new(Source::Raw(r"\bhot\b"), Box::new("het"))?,
                Replacement::new(Source::Raw(r"\bhotels\b"), Box::new("change-hooses"))?,
                Replacement::new(Source::Raw(r"\bhotel\b"), Box::new("change-hoose"))?,
                Replacement::new(Source::Raw(r"\bhours\b"), Box::new("oors"))?,
                Replacement::new(Source::Raw(r"\bhour\b"), Box::new("oor"))?,
                Replacement::new(Source::Raw(r"\bhouse\b"), Box::new("hoose"))?,
                Replacement::new(Source::Raw(r"\bhouses\b"), Box::new("hooses"))?,
                Replacement::new(Source::Raw(r"\bhow\b"), Box::new("hou"))?,
                Replacement::new(Source::Raw(r"\bhusband\b"), Box::new("guidman"))?,
                Replacement::new(Source::Raw(r"\bimages\b"), Box::new("photies"))?,
                Replacement::new(Source::Raw(r"\bimage\b"), Box::new("photie"))?,
                Replacement::new(Source::Raw(r"\bimagine\b"), Box::new("jalouse"))?,
                Replacement::new(Source::Raw(r"\bincluding\b"), Box::new("anaw"))?,
                Replacement::new(Source::Raw(r"\bindicates\b"), Box::new("shows"))?,
                Replacement::new(Source::Raw(r"\bindicate\b"), Box::new("show"))?,
                Replacement::new(Source::Raw(r"\binformations\b"), Box::new("speirins"))?,
                Replacement::new(Source::Raw(r"\binformation\b"), Box::new("speirins"))?,
                Replacement::new(Source::Raw(r"\binto\b"), Box::new("intae"))?,
                Replacement::new(Source::Raw(r"\bits\b"), Box::new("tis"))?,
                Replacement::new(Source::Raw(r"\bisn't\b"), Box::new("isna"))?,
                Replacement::new(Source::Raw(r"\bisnt\b"), Box::new("isna"))?,
                Replacement::new(Source::Raw(r"\bjanitors\b"), Box::new("jannies"))?,
                Replacement::new(Source::Raw(r"\bjanitor\b"), Box::new("jannie"))?,
                Replacement::new(Source::Raw(r"\bjobs\b"), Box::new("jabs"))?,
                Replacement::new(Source::Raw(r"\bjoined\b"), Box::new("jyneed"))?,
                Replacement::new(Source::Raw(r"\bjoins\b"), Box::new("jynes"))?,
                Replacement::new(Source::Raw(r"\bjoin\b"), Box::new("jyne"))?,
                Replacement::new(Source::Raw(r"\bjust\b"), Box::new("juist"))?,
                Replacement::new(Source::Raw(r"\bkids\b"), Box::new("bairns"))?,
                Replacement::new(Source::Raw(r"\bkid\b"), Box::new("bairn"))?,
                Replacement::new(Source::Raw(r"\bkills\b"), Box::new("murdurrs"))?,
                Replacement::new(Source::Raw(r"\bkiller\b"), Box::new("murdurrur"))?,
                Replacement::new(Source::Raw(r"\bkilled\b"), Box::new("murdurred"))?,
                Replacement::new(Source::Raw(r"\bkill\b"), Box::new("murdurr"))?,
                Replacement::new(Source::Raw(r"\bkitchens\b"), Box::new("sculleries"))?,
                Replacement::new(Source::Raw(r"\bkitchen\b"), Box::new("scullery"))?,
                Replacement::new(Source::Raw(r"\bknows\b"), Box::new("kens"))?,
                Replacement::new(Source::Raw(r"\bknow\b"), Box::new("ken"))?,
                Replacement::new(Source::Raw(r"\bknown\b"), Box::new("kent"))?,
                Replacement::new(Source::Raw(r"\blanguages\b"), Box::new("leids"))?,
                Replacement::new(Source::Raw(r"\blanguage\b"), Box::new("leid"))?,
                Replacement::new(Source::Raw(r"\blarger\b"), Box::new("lairger"))?,
                Replacement::new(Source::Raw(r"\blargest\b"), Box::new("lairgest"))?,
                Replacement::new(Source::Raw(r"\blarge\b"), Box::new("lairge"))?,
                Replacement::new(Source::Raw(r"\blast\b"), Box::new("lest"))?,
                Replacement::new(Source::Raw(r"\blater\b"), Box::new("efter"))?,
                Replacement::new(Source::Raw(r"\blaughing\b"), Box::new("roarin"))?,
                Replacement::new(Source::Raw(r"\blaugh\b"), Box::new("roar"))?,
                Replacement::new(Source::Raw(r"\blawyers\b"), Box::new("advocates"))?,
                Replacement::new(Source::Raw(r"\blawyer\b"), Box::new("advocate"))?,
                Replacement::new(Source::Raw(r"\blead\b"), Box::new("leid"))?,
                Replacement::new(Source::Raw(r"\bleading\b"), Box::new("leidin"))?,
                Replacement::new(Source::Raw(r"\bleaving\b"), Box::new("leaing"))?,
                Replacement::new(Source::Raw(r"\bleave\b"), Box::new("lea"))?,
                Replacement::new(Source::Raw(r"\blet\b"), Box::new("loot"))?,
                Replacement::new(Source::Raw(r"\blegs\b"), Box::new("shanks"))?,
                Replacement::new(Source::Raw(r"\bleg\b"), Box::new("shank"))?,
                Replacement::new(Source::Raw(r"\bdevil\b"), Box::new("deuce"))?,
                Replacement::new(Source::Raw(r"\bdevils\b"), Box::new("deuces"))?,
                Replacement::new(Source::Raw(r"\blying\b"), Box::new("liein"))?,
                Replacement::new(Source::Raw(r"\blike\b"), Box::new("lik`"))?,
                Replacement::new(Source::Raw(r"\blikely\b"), Box::new("likelie"))?,
                Replacement::new(Source::Raw(r"\blittle\b"), Box::new("wee"))?,
                Replacement::new(Source::Raw(r"\blonger\b"), Box::new("langer"))?,
                Replacement::new(Source::Raw(r"\blongest\b"), Box::new("langest"))?,
                Replacement::new(Source::Raw(r"\blong\b"), Box::new("lang"))?,
                Replacement::new(Source::Raw(r"\blooking\b"), Box::new("keeking"))?,
                Replacement::new(Source::Raw(r"\blooked\b"), Box::new("keeked"))?,
                Replacement::new(Source::Raw(r"\blook\b"), Box::new("keek"))?,
                Replacement::new(Source::Raw(r"\bloved\b"), Box::new("loued"))?,
                Replacement::new(Source::Raw(r"\bloving\b"), Box::new("louing"))?,
                Replacement::new(Source::Raw(r"\blove\b"), Box::new("loue"))?,
                Replacement::new(Source::Raw(r"\bmakes\b"), Box::new("mak`s"))?,
                Replacement::new(Source::Raw(r"\bmake\b"), Box::new("mak`"))?,
                Replacement::new(Source::Raw(r"\bmen\b"), Box::new("jimmies"))?,
                Replacement::new(Source::Raw(r"\bmanage\b"), Box::new("guide"))?,
                Replacement::new(Source::Raw(r"\bmanagers\b"), Box::new("high heid yins"))?,
                Replacement::new(Source::Raw(r"\bmanager\b"), Box::new("high heid yin"))?,
                Replacement::new(Source::Raw(r"\bmany\b"), Box::new("mony"))?,
                Replacement::new(Source::Raw(r"\bmay\b"), Box::new("mey"))?,
                Replacement::new(Source::Raw(r"\bmarkets\b"), Box::new("merkats"))?,
                Replacement::new(Source::Raw(r"\bmarket\b"), Box::new("merkat"))?,
                Replacement::new(Source::Raw(r"\bmarriages\b"), Box::new("mairriages"))?,
                Replacement::new(Source::Raw(r"\bmarriage\b"), Box::new("mairriage"))?,
                Replacement::new(Source::Raw(r"\bmatters\b"), Box::new("maiters"))?,
                Replacement::new(Source::Raw(r"\bmatter\b"), Box::new("maiter"))?,
                Replacement::new(Source::Raw(r"\bmaybe\b"), Box::new("mibbie"))?,
                Replacement::new(Source::Raw(r"\bmeetings\b"), Box::new("meetins"))?,
                Replacement::new(Source::Raw(r"\bmeeting\b"), Box::new("meetin"))?,
                Replacement::new(Source::Raw(r"\bmethods\b"), Box::new("ways"))?,
                Replacement::new(Source::Raw(r"\bmethod\b"), Box::new("way"))?,
                Replacement::new(Source::Raw(r"\bmight\b"), Box::new("micht"))?,
                Replacement::new(Source::Raw(r"\bmind\b"), Box::new("mynd"))?,
                Replacement::new(Source::Raw(r"\bminer\b"), Box::new("pickman"))?,
                Replacement::new(Source::Raw(r"\bminers\b"), Box::new("pickmen"))?,
                Replacement::new(Source::Raw(r"\bmoney\b"), Box::new("dosh"))?,
                Replacement::new(Source::Raw(r"\bmonths\b"), Box::new("munths"))?,
                Replacement::new(Source::Raw(r"\bmonth\b"), Box::new("munth"))?,
                Replacement::new(Source::Raw(r"\bmore\b"), Box::new("mair"))?,
                Replacement::new(Source::Raw(r"\bmornings\b"), Box::new("mornin`s"))?,
                Replacement::new(Source::Raw(r"\bmorning\b"), Box::new("mornin`"))?,
                Replacement::new(Source::Raw(r"\bmost\b"), Box::new("maist"))?,
                Replacement::new(Source::Raw(r"\bmothers\b"), Box::new("mithers"))?,
                Replacement::new(Source::Raw(r"\bmother\b"), Box::new("mither"))?,
                Replacement::new(Source::Raw(r"\bmouths\b"), Box::new("geggies"))?,
                Replacement::new(Source::Raw(r"\bmouth\b"), Box::new("geggy"))?,
                Replacement::new(Source::Raw(r"\bmoves\b"), Box::new("shifts"))?,
                Replacement::new(Source::Raw(r"\bmove\b"), Box::new("shift"))?,
                Replacement::new(Source::Raw(r"\bmuch\b"), Box::new("muckle"))?,
                Replacement::new(Source::Raw(r"\bmust\b"), Box::new("mist"))?,
                Replacement::new(Source::Raw(r"\bmy\b"), Box::new("ma"))?,
                Replacement::new(Source::Raw(r"\bmyself\b"), Box::new("masell"))?,
                Replacement::new(Source::Raw(r"\bnasty\b"), Box::new("mingin"))?,
                Replacement::new(Source::Raw(r"\bnetworks\b"), Box::new("netwurks"))?,
                Replacement::new(Source::Raw(r"\bnetwork\b"), Box::new("netwurk"))?,
                Replacement::new(Source::Raw(r"\bnever\b"), Box::new("ne`er"))?,
                Replacement::new(Source::Raw(r"\bnew\b"), Box::new("freish"))?,
                Replacement::new(Source::Raw(r"\bnews\b"), Box::new("speirins"))?,
                Replacement::new(Source::Raw(r"\bnext\b"), Box::new("neist"))?,
                Replacement::new(Source::Raw(r"\bnice\b"), Box::new("crakin`"))?,
                Replacement::new(Source::Raw(r"\bnights\b"), Box::new("nichts"))?,
                Replacement::new(Source::Raw(r"\bnight\b"), Box::new("nicht"))?,
                Replacement::new(
                    Source::Raw(r"\bFalse\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("na"), Box::new("aff")],
                    }),
                )?,
                Replacement::new(Source::Raw(r"\bnot\b"), Box::new("nae"))?,
                Replacement::new(Source::Raw(r"\bnothing\b"), Box::new("neithin'"))?,
                Replacement::new(Source::Raw(r"\bnow\b"), Box::new("noo"))?,
                Replacement::new(Source::Raw(r"\bnumbers\b"), Box::new("nummers"))?,
                Replacement::new(Source::Raw(r"\bnumber\b"), Box::new("nummer"))?,
                Replacement::new(Source::Raw(r"\bof\b"), Box::new("o`"))?,
                Replacement::new(Source::Raw(r"\boffices\b"), Box::new("affices"))?,
                Replacement::new(Source::Raw(r"\boffice\b"), Box::new("affice"))?,
                Replacement::new(Source::Raw(r"\bofficers\b"), Box::new("boabies"))?,
                Replacement::new(Source::Raw(r"\bofficer\b"), Box::new("boaby"))?,
                Replacement::new(Source::Raw(r"\boften\b"), Box::new("aften"))?,
                Replacement::new(Source::Raw(r"\boh\b"), Box::new("och"))?,
                Replacement::new(Source::Raw(r"\bok\b"), Box::new("a`richt"))?,
                Replacement::new(Source::Raw(r"\bold\b"), Box::new("auld"))?,
                Replacement::new(Source::Raw(r"\boil\b"), Box::new("ile"))?,
                Replacement::new(Source::Raw(r"\bonce\b"), Box::new("wance"))?,
                Replacement::new(Source::Raw(r"\bone\b"), Box::new("wan"))?,
                Replacement::new(Source::Raw(r"\bonly\b"), Box::new("ainlie"))?,
                Replacement::new(Source::Raw(r"\bother\b"), Box::new("ither"))?,
                Replacement::new(Source::Raw(r"\bothers\b"), Box::new("ithers"))?,
                Replacement::new(Source::Raw(r"\bours\b"), Box::new("oors"))?,
                Replacement::new(Source::Raw(r"\bour\b"), Box::new("oor"))?,
                Replacement::new(Source::Raw(r"\bout\b"), Box::new("oot"))?,
                Replacement::new(Source::Raw(r"\boutside\b"), Box::new("ootdoors"))?,
                Replacement::new(Source::Raw(r"\bover\b"), Box::new("ower"))?,
                Replacement::new(Source::Raw(r"\bowns\b"), Box::new("ains"))?,
                Replacement::new(Source::Raw(r"\bown\b"), Box::new("ain"))?,
                Replacement::new(Source::Raw(r"\bowners\b"), Box::new("gaffers"))?,
                Replacement::new(Source::Raw(r"\bowner\b"), Box::new("gaffer"))?,
                Replacement::new(Source::Raw(r"\bpaintings\b"), Box::new("pentins"))?,
                Replacement::new(Source::Raw(r"\bpainting\b"), Box::new("pentin"))?,
                Replacement::new(Source::Raw(r"\bparts\b"), Box::new("pairts"))?,
                Replacement::new(Source::Raw(r"\bpart\b"), Box::new("pairt"))?,
                Replacement::new(Source::Raw(r"\bpartners\b"), Box::new("bidies"))?,
                Replacement::new(Source::Raw(r"\bpartner\b"), Box::new("bidie"))?,
                Replacement::new(Source::Raw(r"\bparty\b"), Box::new("pairtie"))?,
                Replacement::new(Source::Raw(r"\bpass\b"), Box::new("bygae"))?,
                Replacement::new(Source::Raw(r"\bpast\b"), Box::new("bygane"))?,
                Replacement::new(Source::Raw(r"\bpeoples\b"), Box::new("fowks"))?,
                Replacement::new(Source::Raw(r"\bpeople\b"), Box::new("fowk"))?,
                Replacement::new(Source::Raw(r"\bperhaps\b"), Box::new("mibbie"))?,
                Replacement::new(Source::Raw(r"\bperson\b"), Box::new("body"))?,
                Replacement::new(Source::Raw(r"\bphones\b"), Box::new("phanes"))?,
                Replacement::new(Source::Raw(r"\bphone\b"), Box::new("phane"))?,
                Replacement::new(Source::Raw(r"\bplaces\b"), Box::new("steids"))?,
                Replacement::new(Source::Raw(r"\bplace\b"), Box::new("steid"))?,
                Replacement::new(Source::Raw(r"\bplays\b"), Box::new("speils"))?,
                Replacement::new(Source::Raw(r"\bplay\b"), Box::new("speil"))?,
                Replacement::new(Source::Raw(r"\bpolice\b"), Box::new("polis"))?,
                Replacement::new(Source::Raw(r"\bpoor\b"), Box::new("brassic"))?,
                Replacement::new(Source::Raw(r"\bpopular\b"), Box::new("weel-kent"))?,
                Replacement::new(Source::Raw(r"\bproblems\b"), Box::new("kinches"))?,
                Replacement::new(Source::Raw(r"\bproblem\b"), Box::new("kinch"))?,
                Replacement::new(
                    Source::Raw(r"\bprofessionals\b"),
                    Box::new("perfaissionals"),
                )?,
                Replacement::new(Source::Raw(r"\bprofessional\b"), Box::new("perfaissional"))?,
                Replacement::new(Source::Raw(r"\bprograms\b"), Box::new("progrums"))?,
                Replacement::new(Source::Raw(r"\bprogram\b"), Box::new("progrum"))?,
                Replacement::new(Source::Raw(r"\bprovides\b"), Box::new("gies"))?,
                Replacement::new(Source::Raw(r"\bprovide\b"), Box::new("gie"))?,
                Replacement::new(Source::Raw(r"\bprison\b"), Box::new("preeson"))?,
                Replacement::new(Source::Raw(r"\bImprisonment\b"), Box::new("impreesonment"))?,
                Replacement::new(Source::Raw(r"\bprisoner\b"), Box::new("preesoner"))?,
                Replacement::new(Source::Raw(r"\bput\b"), Box::new("pat"))?,
                Replacement::new(Source::Raw(r"\bquestions\b"), Box::new("quaistions"))?,
                Replacement::new(Source::Raw(r"\bquestion\b"), Box::new("quaistion"))?,
                Replacement::new(Source::Raw(r"\bquite\b"), Box::new("ferr"))?,
                Replacement::new(Source::Raw(r"\bradios\b"), Box::new("trannies"))?,
                Replacement::new(Source::Raw(r"\bradio\b"), Box::new("tranny"))?,
                Replacement::new(Source::Raw(r"\brather\b"), Box::new("ower"))?,
                Replacement::new(Source::Raw(r"\bready\b"), Box::new("duin"))?,
                Replacement::new(Source::Raw(r"\breally\b"), Box::new("pure"))?,
                Replacement::new(Source::Raw(r"\bred\b"), Box::new("rid"))?,
                Replacement::new(Source::Raw(r"\brelationships\b"), Box::new("kinships"))?,
                Replacement::new(Source::Raw(r"\brelationship\b"), Box::new("kinship"))?,
                Replacement::new(Source::Raw(r"\bremember\b"), Box::new("mind"))?,
                Replacement::new(Source::Raw(r"\bremembered\b"), Box::new("minded"))?,
                Replacement::new(Source::Raw(r"\brights\b"), Box::new("richts"))?,
                Replacement::new(Source::Raw(r"\bright\b"), Box::new("richt"))?,
                Replacement::new(Source::Raw(r"\broles\b"), Box::new("parts"))?,
                Replacement::new(Source::Raw(r"\brole\b"), Box::new("part"))?,
                Replacement::new(Source::Raw(r"\bround\b"), Box::new("ruund"))?,
                Replacement::new(Source::Raw(r"\bsame\b"), Box::new("identical"))?,
                Replacement::new(Source::Raw(r"\bschools\b"), Box::new("schuils"))?,
                Replacement::new(Source::Raw(r"\bschool\b"), Box::new("schuil"))?,
                Replacement::new(Source::Raw(r"\bscores\b"), Box::new("hampden roars"))?,
                Replacement::new(Source::Raw(r"\bscore\b"), Box::new("hampden roar"))?,
                Replacement::new(Source::Raw(r"\bscuffed\b"), Box::new("scotched"))?,
                Replacement::new(Source::Raw(r"\bseasons\b"), Box::new("seezins"))?,
                Replacement::new(Source::Raw(r"\bseason\b"), Box::new("seezin"))?,
                Replacement::new(Source::Raw(r"\bsecurity\b"), Box::new("polis"))?,
                Replacement::new(Source::Raw(r"\bseconds\b"), Box::new("seiconts"))?,
                Replacement::new(Source::Raw(r"\bsecond\b"), Box::new("seicont"))?,
                Replacement::new(Source::Raw(r"\bseveral\b"), Box::new("loads"))?,
                Replacement::new(Source::Raw(r"\bshaked\b"), Box::new("shoogled"))?,
                Replacement::new(Source::Raw(r"\bshakes\b"), Box::new("shoogles"))?,
                Replacement::new(Source::Raw(r"\bshake\b"), Box::new("shoogle"))?,
                Replacement::new(Source::Raw(r"\bshould\b"), Box::new("shuid"))?,
                Replacement::new(Source::Raw(r"\bshows\b"), Box::new("shaws"))?,
                Replacement::new(Source::Raw(r"\bshowed\b"), Box::new("shawed"))?,
                Replacement::new(Source::Raw(r"\bshow\b"), Box::new("shaw"))?,
                Replacement::new(Source::Raw(r"\bsince\b"), Box::new("sin"))?,
                Replacement::new(Source::Raw(r"\bsmall\b"), Box::new("wee"))?,
                Replacement::new(Source::Raw(r"\bspoke\b"), Box::new("spak"))?,
                Replacement::new(Source::Raw(r"\bso\b"), Box::new("sae"))?,
                Replacement::new(Source::Raw(r"\bsoldiers\b"), Box::new("fighters"))?,
                Replacement::new(Source::Raw(r"\bsoldier\b"), Box::new("fighter"))?,
                Replacement::new(Source::Raw(r"\bsometimes\b"), Box::new("whiles"))?,
                Replacement::new(Source::Raw(r"\bsomewhat\b"), Box::new("somewhit"))?,
                Replacement::new(Source::Raw(r"\bsouth\b"), Box::new("sooth"))?,
                Replacement::new(Source::Raw(r"\bsore\b"), Box::new("sair"))?,
                Replacement::new(Source::Raw(r"\bstands\b"), Box::new("stauns"))?,
                Replacement::new(Source::Raw(r"\bstand\b"), Box::new("staun"))?,
                Replacement::new(Source::Raw(r"\bstars\b"), Box::new("starns"))?,
                Replacement::new(Source::Raw(r"\bstar\b"), Box::new("starn"))?,
                Replacement::new(Source::Raw(r"\bstarts\b"), Box::new("stairts"))?,
                Replacement::new(Source::Raw(r"\bstart\b"), Box::new("stairt"))?,
                Replacement::new(Source::Raw(r"\bstays\b"), Box::new("bides"))?,
                Replacement::new(Source::Raw(r"\bstay\b"), Box::new("bade"))?,
                Replacement::new(Source::Raw(r"\bstops\b"), Box::new("stoaps"))?,
                Replacement::new(Source::Raw(r"\bstop\b"), Box::new("stoap"))?,
                Replacement::new(Source::Raw(r"\bstores\b"), Box::new("hains"))?,
                Replacement::new(Source::Raw(r"\bstore\b"), Box::new("hain"))?,
                Replacement::new(Source::Raw(r"\bstruck\b"), Box::new("strak"))?,
                Replacement::new(Source::Raw(r"\bstreets\b"), Box::new("wynds"))?,
                Replacement::new(Source::Raw(r"\bstreet\b"), Box::new("wynd"))?,
                Replacement::new(Source::Raw(r"\bstrong\b"), Box::new("pure tough"))?,
                Replacement::new(Source::Raw(r"\bstyles\b"), Box::new("pure classes"))?,
                Replacement::new(Source::Raw(r"\bstyle\b"), Box::new("pure class"))?,
                Replacement::new(Source::Raw(r"\bsuch\b"), Box::new("sic"))?,
                Replacement::new(Source::Raw(r"\btable\b"), Box::new("buird"))?,
                Replacement::new(Source::Raw(r"\btables\b"), Box::new("buirds"))?,
                Replacement::new(Source::Raw(r"\btakes\b"), Box::new("tak`s"))?,
                Replacement::new(Source::Raw(r"\btake\b"), Box::new("tak`"))?,
                Replacement::new(Source::Raw(r"\btalks\b"), Box::new("blethers"))?,
                Replacement::new(Source::Raw(r"\btalk\b"), Box::new("blether"))?,
                Replacement::new(Source::Raw(r"\btasks\b"), Box::new("hings"))?,
                Replacement::new(Source::Raw(r"\btask\b"), Box::new("hing"))?,
                Replacement::new(Source::Raw(r"\bteams\b"), Box::new("gangs"))?,
                Replacement::new(Source::Raw(r"\bteam\b"), Box::new("gang"))?,
                Replacement::new(Source::Raw(r"\btelevisions\b"), Box::new("tellyboxes"))?,
                Replacement::new(Source::Raw(r"\btelevision\b"), Box::new("tellybox"))?,
                Replacement::new(Source::Raw(r"\bterminal\b"), Box::new("terminus"))?,
                Replacement::new(Source::Raw(r"\bthe\b"), Box::new("th`"))?,
                Replacement::new(Source::Raw(r"\btheir\b"), Box::new("thair"))?,
                Replacement::new(Source::Raw(r"\bthem\b"), Box::new("thaim"))?,
                Replacement::new(Source::Raw(r"\bthere\b"), Box::new("thare"))?,
                Replacement::new(Source::Raw(r"\bthese\b"), Box::new("thae"))?,
                Replacement::new(Source::Raw(r"\bthey\b"), Box::new("thay"))?,
                Replacement::new(Source::Raw(r"\bthings\b"), Box::new("hings"))?,
                Replacement::new(Source::Raw(r"\bthing\b"), Box::new("hing"))?,
                Replacement::new(Source::Raw(r"\bthose\b"), Box::new("they"))?,
                Replacement::new(Source::Raw(r"\bthrough\b"), Box::new("thro`"))?,
                Replacement::new(Source::Raw(r"\bthroughout\b"), Box::new("throo`oot"))?,
                Replacement::new(Source::Raw(r"\bthrow\b"), Box::new("chuck"))?,
                Replacement::new(Source::Raw(r"\bthrew\b"), Box::new("chucked"))?,
                Replacement::new(Source::Raw(r"\bto\b"), Box::new("tae"))?,
                Replacement::new(Source::Raw(r"\btoday\b"), Box::new("th`day"))?,
                Replacement::new(Source::Raw(r"\btogether\b"), Box::new("th`gither"))?,
                Replacement::new(Source::Raw(r"\btonight\b"), Box::new("th`nicht"))?,
                Replacement::new(Source::Raw(r"\btoo\b"), Box::new("tae"))?,
                Replacement::new(Source::Raw(r"\btold\b"), Box::new("telt"))?,
                Replacement::new(Source::Raw(r"\btops\b"), Box::new("taps"))?,
                Replacement::new(Source::Raw(r"\btop\b"), Box::new("tap"))?,
                Replacement::new(Source::Raw(r"\btotal\b"), Box::new("tot"))?,
                Replacement::new(Source::Raw(r"\btowns\b"), Box::new("touns"))?,
                Replacement::new(Source::Raw(r"\btown\b"), Box::new("toun"))?,
                Replacement::new(Source::Raw(r"\btough\b"), Box::new("hard"))?,
                Replacement::new(Source::Raw(r"\btraitors\b"), Box::new("quislings"))?,
                Replacement::new(
                    Source::Raw(r"\btraitor\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("quisling"), Box::new("traitor")],
                    }),
                )?,
                Replacement::new(Source::Raw(r"\btroubles\b"), Box::new("trauchles"))?,
                Replacement::new(Source::Raw(r"\btrouble\b"), Box::new("trauchle"))?,
                Replacement::new(Source::Raw(r"\bturds\b"), Box::new("jobbies"))?,
                Replacement::new(Source::Raw(r"\bturd\b"), Box::new("jobbie"))?,
                Replacement::new(Source::Raw(r"\bturn\b"), Box::new("caw"))?,
                Replacement::new(Source::Raw(r"\bTVs\b"), Box::new("tellies"))?,
                Replacement::new(Source::Raw(r"\bTV\b"), Box::new("telly"))?,
                Replacement::new(Source::Raw(r"\btwo\b"), Box::new("twa"))?,
                Replacement::new(Source::Raw(r"\bunderstand\b"), Box::new("ken"))?,
                Replacement::new(Source::Raw(r"\buntil\b"), Box::new("`til"))?,
                Replacement::new(Source::Raw(r"\buses\b"), Box::new("uises"))?,
                Replacement::new(Source::Raw(r"\buse\b"), Box::new("uise"))?,
                Replacement::new(Source::Raw(r"\busually\b"), Box::new("forordinar"))?,
                Replacement::new(Source::Raw(r"\bvery\b"), Box::new("gey"))?,
                Replacement::new(Source::Raw(r"\bvictims\b"), Box::new("sittin` ducks"))?,
                Replacement::new(Source::Raw(r"\bvictim\b"), Box::new("sittin` duck"))?,
                Replacement::new(Source::Raw(r"\bviews\b"), Box::new("sichts"))?,
                Replacement::new(Source::Raw(r"\bview\b"), Box::new("sicht"))?,
                Replacement::new(Source::Raw(r"\bwas\b"), Box::new("wis"))?,
                Replacement::new(Source::Raw(r"\bwasn't\b"), Box::new("wisna"))?,
                Replacement::new(Source::Raw(r"\bwasnt\b"), Box::new("wisna"))?,
                Replacement::new(Source::Raw(r"\bwalks\b"), Box::new("daunders"))?,
                Replacement::new(Source::Raw(r"\bwalk\b"), Box::new("daunder"))?,
                Replacement::new(Source::Raw(r"\bwalked\b"), Box::new("daundered"))?,
                Replacement::new(Source::Raw(r"\bwalking\b"), Box::new("daunderin"))?,
                Replacement::new(Source::Raw(r"\bwall\b"), Box::new("dyke"))?,
                Replacement::new(Source::Raw(r"\bwant\b"), Box::new("waant"))?,
                Replacement::new(Source::Raw(r"\bwater\b"), Box::new("watter"))?,
                Replacement::new(Source::Raw(r"\bway\b"), Box::new("wey"))?,
                Replacement::new(Source::Raw(r"\bwarden\b"), Box::new("screw"))?,
                Replacement::new(Source::Raw(r"\bwell\b"), Box::new("weel"))?,
                Replacement::new(Source::Raw(r"\bwere\b"), Box::new("war"))?,
                Replacement::new(Source::Raw(r"\bwest\b"), Box::new("wast"))?,
                Replacement::new(Source::Raw(r"\bwhat\b"), Box::new("whit"))?,
                Replacement::new(Source::Raw(r"\bwhatever\b"), Box::new("whitevur"))?,
                Replacement::new(Source::Raw(r"\bwhen\b"), Box::new("whin"))?,
                Replacement::new(Source::Raw(r"\bwhere\b"), Box::new("whaur"))?,
                Replacement::new(Source::Raw(r"\bwhether\b"), Box::new("whither"))?,
                Replacement::new(Source::Raw(r"\bwhich\b"), Box::new("whilk"))?,
                Replacement::new(Source::Raw(r"\bwho\b"), Box::new("wha"))?,
                Replacement::new(Source::Raw(r"\bwhole\b"), Box::new("hail"))?,
                Replacement::new(Source::Raw(r"\bwhom\b"), Box::new("wham"))?,
                Replacement::new(Source::Raw(r"\bwhose\b"), Box::new("wha`s"))?,
                Replacement::new(Source::Raw(r"\bwife\b"), Box::new("guidwife"))?,
                Replacement::new(Source::Raw(r"\bwives\b"), Box::new("guidwives"))?,
                Replacement::new(Source::Raw(r"\bwind\b"), Box::new("win`"))?,
                Replacement::new(Source::Raw(r"\bwindow\b"), Box::new("windae"))?,
                Replacement::new(Source::Raw(r"\bwindows\b"), Box::new("windaes"))?,
                Replacement::new(Source::Raw(r"\bwith\b"), Box::new("wi`"))?,
                Replacement::new(Source::Raw(r"\bwithin\b"), Box::new("wi`in"))?,
                Replacement::new(Source::Raw(r"\bwithout\b"), Box::new("wi`oot"))?,
                Replacement::new(Source::Raw(r"\bwoman\b"), Box::new("wifie"))?,
                Replacement::new(Source::Raw(r"\bwomen\b"), Box::new("Wummin"))?,
                Replacement::new(Source::Raw(r"\bwork\b"), Box::new("wirk"))?,
                Replacement::new(Source::Raw(r"\bwords\b"), Box::new("Wurds"))?,
                Replacement::new(Source::Raw(r"\bworld\b"), Box::new("warl"))?,
                Replacement::new(Source::Raw(r"\bworldly\b"), Box::new("war'ly"))?,
                Replacement::new(Source::Raw(r"\bworking\b"), Box::new("wirkin"))?,
                Replacement::new(Source::Raw(r"\bwould\b"), Box::new("wid"))?,
                Replacement::new(Source::Raw(r"\bworse\b"), Box::new("waur"))?,
                Replacement::new(Source::Raw(r"\bruined\b"), Box::new("clapped"))?,
                Replacement::new(Source::Raw(r"\bwrong\b"), Box::new("wrang"))?,
                Replacement::new(Source::Raw(r"\byard\b"), Box::new("yaird"))?,
                Replacement::new(Source::Raw(r"\byeah\b"), Box::new("aye"))?,
                Replacement::new(
                    Source::Raw(r"\bTrue\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("aye"), Box::new("oan")],
                    }),
                )?,
                Replacement::new(Source::Raw(r"\byet\b"), Box::new("yit"))?,
                Replacement::new(Source::Raw(r"\byou\b"), Box::new("ye"))?,
                Replacement::new(Source::Raw(r"\byour\b"), Box::new("yer"))?,
                Replacement::new(Source::Raw(r"\byoure\b"), Box::new("yer'r"))?,
                Replacement::new(Source::Raw(r"\byourself\b"), Box::new("yersel`"))?,
                Replacement::new(Source::Raw(r"\bquiet\b"), Box::new("cannie"))?,
                Replacement::new(Source::Raw(r"\bi\b"), Box::new("a"))?,
                Replacement::new(Source::Raw(r"\bive\b"), Box::new("a've"))?,
                Replacement::new(Source::Raw(r"\bim\b"), Box::new("a'm"))?,
                Replacement::new(Source::Raw(r"\bit\b"), Box::new("et"))?,
                Replacement::new(Source::Raw(r"\bshit\b"), Box::new("shite"))?,
                Replacement::new(Source::Raw(r"\bshitsec\b"), Box::new("shitesec"))?,
                Replacement::new(Source::Raw(r"\balright\b"), Box::new("awricht"))?,
                Replacement::new(Source::Raw(r"\bcrazy\b"), Box::new("doolally"))?,
                Replacement::new(
                    Source::Raw(r"\bidiot\b"),
                    Box::new(MultiTarget {
                        replacement: vec![
                            Box::new("eejit"),
                            Box::new("numpty"),
                            Box::new("mongo"),
                            Box::new("neep"),
                        ],
                    }),
                )?,
                Replacement::new(
                    Source::Raw(r"\bidiots\b"),
                    Box::new(MultiTarget {
                        replacement: vec![
                            Box::new("eejits"),
                            Box::new("numptys"),
                            Box::new("mongos"),
                            Box::new("neeps"),
                        ],
                    }),
                )?,
                Replacement::new(Source::Raw(r"\bugly\b"), Box::new("hackit"))?,
                Replacement::new(Source::Raw(r"\btired\b"), Box::new("knackert"))?,
                Replacement::new(Source::Raw(r"\bgay\b"), Box::new("bufty"))?,
                Replacement::new(Source::Raw(r"\btesting\b"), Box::new("testin`"))?,
                Replacement::new(Source::Raw(r"\bfuck\b"), Box::new("fook"))?,
                Replacement::new(Source::Raw(r"\bfucking\b"), Box::new("fookin`,feckin"))?,
                Replacement::new(Source::Raw(r"\bfucker\b"), Box::new("fooker"))?,
                Replacement::new(Source::Raw(r"\bfuckers\b"), Box::new("fookers"))?,
                Replacement::new(
                    Source::Raw(r"\bmom\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("maw"), Box::new("mam")],
                    }),
                )?,
                Replacement::new(
                    Source::Raw(r"\bmoms\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("maws"), Box::new("mams")],
                    }),
                )?,
                Replacement::new(
                    Source::Raw(r"\bthrowing\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("chuckin"), Box::new("chuckin'")],
                    }),
                )?,
                Replacement::new(
                    Source::Raw(r"\bfucked\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("fooked"), Box::new("shagged")],
                    }),
                )?,
                Replacement::new(Source::Raw(r"\bass\b"), Box::new("arse"))?,
                Replacement::new(Source::Raw(r"\basses\b"), Box::new("arses"))?,
                Replacement::new(Source::Raw(r"\bbothered\b"), Box::new("arsed"))?,
                Replacement::new(Source::Raw(r"\bdick\b"), Box::new("boaby"))?,
                Replacement::new(Source::Raw(r"\bdicks\b"), Box::new("boabys"))?,
                Replacement::new(Source::Raw(r"\bsomething\b"), Box::new("suhin"))?,
                Replacement::new(Source::Raw(r"\bsomethings\b"), Box::new("suhins"))?,
                Replacement::new(
                    Source::Raw(r"\bboys\b"),
                    Box::new(MultiTarget {
                        replacement: vec![Box::new("lads"), Box::new("laddies")],
                    }),
                )?,
                Replacement::new(
                    Source::Raw(r"\bgirls\b"),
                    Box::new(MultiTarget {
                        replacement: vec![
                            Box::new("lasses"),
                            Box::new("lassies"),
                            Box::new("burds"),
                        ],
                    }),
                )?,
            ],
        })
    }
}
