repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear", "flake8-unused-arguments"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - "uvloop"
          - "python-dotenv"
          - "pink_accents==0.0.4"
          - "discord.py"
          - "sentry_sdk"
          - "asyncpg-stubs @ git+https://github.com/bryanforbes/asyncpg-stubs@c46b93dca927829eca48b0835018eba9f4046132"
