[bot]
token = "NTU2NTI4MDcwNjMxMjI3NDAy.XI1xJF.xl6iW44dagmEjnZVjzBHTL_w-pM"
prefix = "!"

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[sentry]
dsn = "https://ABCD@o546834.example.org/123"

[owners]
# owners are fetched from application info. use this to to add extra owners or override application owners completely
ids = [439205512425504771, 80528701850124288]
# either "combine"  or "overwrite"
mode = "combine"

[db]
path = "/data/pink.db"

[cog.servermyserver]
server = 391987311468085248
user_log_channel = 399649344443383810
all_role = 518862360681906186

[cog.images]
ocr_api_token = "aaa"
