[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 121
atomic = true
combine_as_imports = true
lines_between_types = 1

[tool.mypy]
python_version = "3.10"

show_column_numbers = true
show_error_codes = true

warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
# it is very convenient to return from event handler
# warn_return_any = true

check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_defs = true
# discord models are untyped
# disallow_subclassing_any = true
# some external code is untyped like edgedb
# disallow_untyped_calls = true
disallow_incomplete_defs = true
# all discord.py decorators are untyped
# disallow_untyped_decorators = true
no_implicit_optional = true
# doesnt like edgedb properties
# no_implicit_reexport = true
strict_equality = true


[[tool.mypy.overrides]]
module = [
    "googletrans.*",
    "PIL.*",
]
ignore_missing_imports = true

# seem to require `namespace_packages = true`, but it is currently broken in mypy:
# https://github.com/python/mypy/issues/12257
#
# this doesnt do anything though, unfortunate
[[tool.mypy.overrides]]
module = [
    "discord.ext.*",
]
ignore_errors = true
